name: api_server
description: Exemplo de uso de API
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
mysql_client: any #mantido para acessar o mysql
shelf: ^1.4.1 #Framework HTTP para Dart
shelf_router: ^1.1.0 # Para roteamento das URL's

